### PR TITLE
Create a Fix for #130

### PR DESCRIPTION
**Pull request by itsyourap**
Add Script `RunIfYouLostAppShortcuts.ps1` to run if lost app shortcuts by chance

### CODE REVIEW

**Comment by yujincheng08** [comment]
Actually, I found `pm hide pkg_name` and then `pm unhide pkg_name` can trigger a shortcut creation.
But it seems that pm hide and pm unhide needs root permission. I think sending an installation broadcast should also work?

**Comment by itsyourap** [comment]
Yeah! It does work!

**Comment by yujincheng08** [comment]
Could you change the script to send broadcast instead?

**Comment by itsyourap** [comment]
Well, looks like sending installation broadcast does not work for split apks. So I decided to make this script reinstall the apps without removing the App Data... That takes a few minutes but works fine with all kinds of apk - Standalone and Split

**Comment by yujincheng08** [comment]
Ok, as I tested for split apk (com.tencent.mm), `am broadcast -a "android.intent.action.PACKAGE_ADDED" -d "package:com.tencent.mm"` does work. But it still needs root permission.

**Comment by yujincheng08** [comment]
And I also tested that `pm install -r` works so we don't need to uninstall the packages first.

**Comment by itsyourap** [comment]
Yep! I am using `pm install -r` in my script which does not require root permissions

**Comment by yujincheng08** [comment]
BTW, I think it's better to uninstall the existing official installation after backing up userdata.vhdx and automatically restore it and run your script to restore icons. adb is required though but I think we can add platform-tools in it. And moreover, we previous found a way to enable debug mode of WSA using powershell, you can check previous PR.

**Comment by itsyourap** [comment]
What advantage do we have after we enable Debug Mode of WSA? Also after reading the previous PR, I couldn't find anything related to debug mode... I just found about the development mode being checked.

**Comment by yujincheng08** [comment]
Without debug mode, adb cannot be connected.

**Comment by itsyourap** [comment]
Oh! I call it the developer mode! Anyways.... How do we enable it from PowerShell? The previous PR was only checking if it was enabled or not!

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/MagiskOnWSA/pull/89/files#diff-173145d7ba39d4d25fd2fc4cc87fdc8ddc838bdfd5a278844b081fa1031d16e7R398-R411

**Comment by itsyourap** [comment]
Okay! I get it! Basically I need to modify my script to make it work automatically from `install.ps1` if `userdata.vhdx` was replaced! Am I right?

**Comment by yujincheng08** [comment]
Yes. Just invoke this script from install.ps1

**Comment by yujincheng08** [comment]
Addressed by 42a4f94d286eb5be8000f38c9e6079595e651f94

**Pull request closed without merging**
