### PR TITLE
Fix OpenGApps download

### PR DESCRIPTION
**Pull request by ItzLightyHD**
Just removed that "f" from the `requests.get()` function

### CODE REVIEW

**Comment by yujincheng08** [comment]
What has it fixed?

**Comment by xunzihao** [comment]
I can't download openGapps please fix it! Thank you

**Comment by canyie** [comment]
what's this

**Comment by ItzLightyHD** [comment]
> What has it fixed?

There was a letter before the quotation marks in the `requests.get()` function that won't allow you to get the list of the OpenGApps packages. What I did was to remove that so there are no errors in downloading GApps.

**Comment by yujincheng08** [comment]
> There was a letter before the quotation marks in the `requests.get()` function that won't allow you to get the list of the OpenGApps packages. What I did was to remove that so there are no errors in downloading GApps.

Why `f` would lead to download fail? https://docs.python.org/3/tutorial/inputoutput.html

**Comment by ItzLightyHD** [comment]
I closed the pull request since the download still fails, and I didn't know about the formatted strings.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 755, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 708, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(3911 bytes read, 4281 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 781, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(3911 bytes read, 4281 more expected)', IncompleteRead(3911 bytes read, 4281 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/_temp/d551dfa1-2530-477d-aacc-676ef08b90e6.py", line 11, in <module>
    res = requests.get(f"https://api.opengapps.org/list")
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3911 bytes read, 4281 more expected)', IncompleteRead(3911 bytes read, 4281 more expected))
```

**Comment by yujincheng08** [comment]
Definitely a problem from OpenGApps's side. You will see
1. open opengapps.org in the browser and it keeps querying
2. `curl -v api.opengapps.org/list` in termux and you will see an error

Nothing we can do. I at least report it to opengapps but I am not sure when it will be fixed.

**Comment by yujincheng08** [comment]
Added a fallback method to download opengapps now.

**Pull request closed without merging**
