### PR TITLE
Add option to upload to release

### PR DESCRIPTION
**Pull request by vvb2077**

### CODE REVIEW

**Comment by vvb2060** [comment]
https://docs.github.com/cn/site-policy/acceptable-use-policies/github-impersonation

**Comment by canyie** [comment]
Who are you

**Comment by canyie** [comment]
？？？

**Comment by vvb2060** [comment]
???

**Comment by PeterNjeim** [comment]
Unfortunately this will create a new release for each new file. Release assets should be grouped into a single release by commit hash.

Also, while I use 7-zip myself, I think it would be better to use a regular zip instead so that the end-user doesn't need to install 7-zip.

**Pull request merged**
