### PR TITLE
compress and uplode as release

### PR DESCRIPTION
**Pull request by AhmedHosnyAdmin**
compressing wsa package into small size (WSA-with-magisk-GApps-pico_2203.40000.3.0_x64_Release-Nightly) only 817 MB
then uploding this file to a new release

for me releases is better as downloading artifacts not supporting resumable downloading and it's impossible to download the file at my net speed, 
but releases supports this
I appreciate your hard work, and hope if you can make an offline version to build offline
Thank you.

### CODE REVIEW

**Comment by vvb2060** [comment]
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by AhmedHosnyAdmin** [comment]
I tried to run it on self hosted runners but it wasn't able to trigger my runner
also tried local action runner but there were a lot of problems doing this too,

**Comment by AhmedHosnyAdmin** [comment]
can you try forking it to another account and run in self hosted runner, because I think there's a problem with self hosted runner

**Comment by vvb2060** [comment]
>  I think there's a problem with self hosted runner

https://github.community/

**Comment by PeterNjeim** [comment]
GitHub Actions artifact download speed is quite slow. I actually recommend that MagiskOnWSA starts hosting sensible defaults on GitHub Releases page instead. That way the forks aren't necessary, and the user can pick and choose from the Releases page instead of waiting for the Action to run. If they require anything specific, they can fork and run the Action themselves. Please consider it.

**Comment by AhmedHosnyAdmin** [comment]
> GitHub Actions artifact download speed is quite slow. I actually recommend that MagiskOnWSA starts hosting sensible defaults on GitHub Releases page instead. That way the forks aren't necessary, and the user can pick and choose from the Releases page instead of waiting for the Action to run. If they require anything specific, they can fork and run the Action themselves. Please consider it.

check this
https://github.com/ahmedhosnypro/MagiskOnWSA/releases/tag/WSA

**Pull request closed without merging**
