### PR TITLE
update hosts ip 

### LINKED ISSUE #479: WSA won't download
image
again don't know how to explain this but here's the image

### PR DESCRIPTION
**Pull request by FZFalzar**
rg-adguard's IP changed, causing the workflow to fail downloading files from MS because it is unable to resolve. fixes #479

### CODE REVIEW

**Comment by yujincheng08** [comment]
This is cf's ip. It won't work.

**Comment by FZFalzar** [comment]
I've just built a copy fine after modifying the hosts file.

**Comment by yujincheng08** [comment]
When the website triggers the Cloudflare Under Attack mode, this ip won't work.

**Comment by yujincheng08** [comment]
I have another way to get the download link. Just wait... I am testing and implementing it.

**Comment by KeeZaMe** [comment]
Thks for your quick reply @yujincheng08! Let us know ;-) Thks for your work and share :)

**Comment by yujincheng08** [comment]
Fixed by #481

**Pull request closed without merging**
