### PR TITLE
Update magisk.yml

### PR DESCRIPTION
**Pull request by Rbhbkkacer**
Add backup old userdata.vhdx in backup folder and restore them after installing.

### CODE REVIEW

**Comment by yujincheng08** [comment]
I dont get it. If the previous installation is ib develop mode, you can uninstall it while preserving userdata.

**Comment by Rbhbkkacer** [comment]
Yes, this is what I did the first time, I made a backup of userdata.vhdx, deleted the old version, installed the new one using Install.ps1, but after installation a new userdata.vhdx was created without the old installed programs. I replaced it with my old file, android started, but there was no android applications in the start menu. 
After all this, I removed WSA, manually installed it via AppxManifest.xml, restored userdata.vhdx before the first launch, and after launching the old installed applications appeared in the start menu.

**Comment by Rbhbkkacer** [comment]
Okay, I'll have to manually install the app.

**Comment by yujincheng08** [comment]
See #130
Amd thats why I dont delete the previous installation but directly reinstall it.

**Pull request closed without merging**
