### PR TITLE
Keep either app store

### PR DESCRIPTION
**Pull request by s1204IT**
#455

### CODE REVIEW

**Comment by yujincheng08** [comment]
You should add info about this here: https://github.com/LSPosed/MagiskOnWSA/blob/1f3721dbd941a096e53a0b14001ab1a4ae2759f2/.github/workflows/magisk.yml#L51

**Comment by s1204IT** [comment]
I would like to see an example of your modifications to my commit.

**Review by TrainG74 — COMMENTED** [review]
just trying to download google play app on this poor ass old computer smh

**Comment by s1204IT** [comment]
> just trying to download google play app on this poor ass old computer smh

???
Please explain in a way that is easy for Japanese to understand.

**Comment by s1204IT** [comment]
@yujincheng08 👍

**Comment by s1204IT** [comment]
However, I have noticed that the style can be very bad and that Amazon is not completely eliminated.
I am closing this PR, but I am not against your commit.
I am actually a beginner in many things.
This MagiskOnWSA is my first time writing a workflow.
Thanks to your very detailed advice, I will be able to grow and develop.
Thank you so much!

**Pull request closed without merging**
