### PR TITLE
Skip apps and services that cannot run on WSA

### PR DESCRIPTION
**Pull request by s1204IT**
- Skip copying files(APK, Framework, And more...) for **carrier devices** and **some limited devices**
- - We will make some more serious changes when the official OpenGApps for ***12L*** is released.<br>It also skips applications that are not supported themselves.
- Always install either App Store

Translated by [DeepL](https://deepl.com)

### CODE REVIEW

**Comment by s1204IT** [comment]
@yujincheng08 Tell me why.

**Comment by yujincheng08** [comment]
Just wait for the official release for 12L.

**Comment by s1204IT** [comment]
Have you looked at the details of the commit?

**Comment by yujincheng08** [comment]
Yes. And what? I dont want to also integrate gapps.

**Comment by s1204IT** [comment]
Why it was closed is beyond me.

**Comment by yujincheng08** [comment]
1. All WSA releases from all the 4 release channels are now in Android 12L, so we only integrate pico variant, which does not contain the extra exclusion you add. So they are meaningless until the official opengapps support for Android 12L is released.
2. No default gapps integration.

**Comment by s1204IT** [comment]
I understand.
Then, I will leave the skip for now.
but, What do you mean about **2.**?
https://github.com/LSPosed/MagiskOnWSA/blob/1f3721dbd941a096e53a0b14001ab1a4ae2759f2/.github/workflows/magisk.yml#L37

**Comment by yujincheng08** [comment]
All options are empty if the workflow is not triggered **manually** (like triggered by push).

**Comment by s1204IT** [comment]
I see.
I'm going to go commit it back.

**Pull request closed without merging**
