### PR TITLE
publish the release

### PR DESCRIPTION
**Pull request by AhmedHosnyAdmin**
publish only one release for each wsa version, be able to update files to the same release when choosing different run options.
and there's no more than one release tag for each wsa version.
the name of the current release is: WSA_2203.40000.3.0_Release-Nightly

### CODE REVIEW

**Comment by AhmedHosnyAdmin** [comment]
image

**Comment by yujincheng08** [comment]
no

**Comment by AhmedHosnyAdmin** [comment]
yes

**Comment by Howard20181** [comment]
To update Magisk or Gapps we need to repackage the entire `system.img`, as it is a large part of the WSA it is not necessary to keep the un-updated parts.
To prevent suspected repository abuse, we should not keep old Release assets and should give priority to using Action assets.

**Comment by PeterNjeim** [comment]
Your point is correct, but your conclusion is not. A widely used practice is to update the latest release itself, instead of creating new ones. I believe this is what Ahmed did for his fork initially.

The best solution is run an Action whenever this repo is updated, which will compile versions for both x86 and arm, and possibly a combination of pico GApps, full GApps, and stable Magisk/no Magisk. That would be 8 assets. It would then update the latest release to include these assets. No old assets remain, problem solved

**Comment by Howard20181** [comment]
Why do we need to build all the types?
It's just easier to use for yourself rather than to distribute.

Repositories with high download traffic will affect all forks and upstream.

**Comment by AhmedHosnyAdmin** [comment]
running an automated action to make a new release after updating repo would be best thing ever,
but what about it need to be sophisticated to check if wsa version got a  new updae  even if the repo didn't got an update
and must have some exclusion like updating reedme file

**Comment by AhmedHosnyAdmin** [comment]
> Why do we need to build all the types? It's just easier to use for yourself rather than to distribute.
> 
> Repositories with high download traffic will affect all forks and upstream.

this is going be private in the main repo, not forks

**Comment by AhmedHosnyAdmin** [comment]
like checking if the action repo is running on the main repo or a fork

**Pull request closed without merging**
